# Generated by Django 5.1.4 on 2025-01-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scope_tag_scope_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_article',
        ),
        migrations.AddField(
            model_name='article',
            name='tag_article',
            field=models.ManyToManyField(through='articles.Scope', to='articles.tag'),
        ),
    ]
